# File transfer states
UPD_CONFIRM_UPLOAD = "UPD_CONFIRM_UPLOAD"
UPD_START_UPLOAD = "UPD_START_UPLOAD"
DWN_CONFIRM_DOWNLOAD = "DWN_CONFIRM_DOWNLOAD"
DWN_READY_DOWNLOAD = "DWN_READY_DOWNLOAD"
DWN_START_DOWNLOAD = "DWN_START_DOWNLOAD"
DWN_FINISHED_DOWNLOAD = "DWN_FINISHED_DOWNLOAD"

# Input states
ENTER_USERNAME = "Enter username: "
ENTER_PASSWORD = "Enter password: "
ENTER_COMMANDS = "Enter one of the following commands: CRT, MSG, DLT, EDT, LST, RDT, UPD, DWN, RMV, XIT, SHT: "

# Invalid/error states
INVALID_COMMAND = "Invalid command"
INVALID_PASSWORD = "Invalid password"
INVALID_SYNTAX = "Invalid syntax for "

# Success
SUCCESS = "SUCCESS"

# Error states
ERROR_THREAD_ALREADY_EXISTS = "ERROR_THREAD_ALREADY_EXISTS"
ERROR_THREAD_NOT_EXIST = "ERROR_THREAD_NOT_EXIST"
ERROR_THREAD_EMPTY = "ERROR_THREAD_EMPTY"
ERROR_THREAD_DELETE_NO_PERMS = "ERROR_THREAD_DELETE_NO_PERMS"
ERROR_MESSAGE_MODIFY_NO_PERMS = "ERROR_MESSAGE_MODIFY_NO_PERMS"
ERROR_MESSAGE_NUMBER_INVALID = "ERROR_MESSAGE_NUMBER_INVALID"
ERROR_MESSAGE_NOT_FOUND = "ERROR_MESSAGE_NOT_FOUND"
ERROR_DOWNLOAD_FILE_NOT_FOUND = "ERROR_DOWNLOAD_FILE_NOT_FOUND"
ERROR_INTERNAL_ERROR = "ERROR_INTERNAL_ERROR"

# Connection states
CLIENT_CONNECTED = "Client connected"
WELCOME = "Welcome to the forum"
EXIT_CONNECTION = "Goodbye"
